# Search the cache for all quotes from DeviCat and list them
import os
import re
from pprint import pprint
import megaclip
quotes = []

try:
	import sys
	sys.path.append("../shed")
	import emotify
except ImportError:
	# Can't find emotify? No probs, just don't convert them.
	def convert_emotes(msg): return msg
else:
	# Activate BTTV and FFZ emotes from DeviCat's channel
	emotify.load_bttv("devicat")
	emotify.load_ffz("54212603")
	from emotify import convert_emotes # More convenient to have just the function

def find_quotes(video):
	info = megaclip.get_video_info(video, cache_only=True)
	if info["metadata"]["channel"]["name"] not in {"devicat", "devi_cat"}: return
	print("Scanning video %s..." % video)
	for msg in info["comments"]:
		if msg["commenter"]["name"] != "cutiecakebot": continue
		m = re.match("#([0-9]+): (.*)$", msg["message"]["body"])
		if not m: continue
		idx = int(m.group(1))
		if not idx: raise ValueError("Something wrong in the data for this line: %r" % msg["message"]["body"])
		quotes.extend([None] * (idx - len(quotes) + 1))
		quotes[idx] = m.group(2)

for fn in sorted(os.listdir("cache")):
	find_quotes(fn.replace(".json", ""))

assert quotes[0] is None # There should be no quote numbered 0
assert quotes[-1] is not None #  ... and we should have slots only for what we use

with open("../devicatoutlet.github.io/quotes.md", "w") as f:
	print("""# Twitch Quotes

<!-- This file is generated by deviquotes.py from the MegaClip project, and
should not be edited manually. -->
<style>img {display: inline-block;} li {line-height: 35px;}</style>

During live streams, funny things that people say can be recorded for posterity
by CutieCakeBot and the mod team. So far, %d quotes have been recorded. Most of
them are listed below; to see the others, ask CutieCakeBot for a quote with the
command `!quote N` for some number N.

""" % (len(quotes)-1), file=f)
	missing_since = 0
	tot_missing = -1 # Ignore the shim
	longest_span = 0, 0, 0
	for idx, quote in enumerate(quotes):
		if quote is None:
			if not missing_since: missing_since = idx
			tot_missing += 1
			continue
		if missing_since:
			span = idx - missing_since
			if span > longest_span[0]: longest_span = span, missing_since, idx-1
			if span == 1:
				print("* <missing quote %d, ask CCB for it please>" % missing_since, file=f)
			else:
				print("* <missing quotes %d-%d, please ask CCB for them>" % (missing_since, idx - 1), file=f)
			missing_since = None
		print("* %d: %s" % (idx, convert_emotes(quote)), file=f)
	print("""
This list is missing %d quotes, plus any that have been recently added.
""" % tot_missing, file=f)
print("Longest span of unknown quotes is %d: %d-%d" % longest_span)
